config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api, defaults: { format: :json } do
    as :user do
      post   "/sign-in"  => "sessions#create"
      delete "/sign-out" => "sessions#destroy"
    end
    resources :features, only: :create
    resources :results, only: :create
  end

  resource :home, only: :show
  resources :features, only: :index do
    resources :results, only: :index
  end
  resources :test_runs, only: %i[index show]
  root to: 'home#show'
end

app/models/application_record.rb
# frozen_string_literal: true

# top level model class
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feature.rb
# frozen_string_literal: true

# model for holding general information about features
class Feature < ApplicationRecord
  has_many :results, dependent: :destroy

  validates :rspec_id, :description, presence: true

  def status
    results.first.passed ? 'passing' : 'failing'
  end

  def last_passed
    last_passing = results.passing.first
    last_passing ? last_passing.created_at.to_fs(:long) : 'n/a'
  end
end

app/models/result.rb
# frozen_string_literal: true

# model for individual results of each feature
class Result < ApplicationRecord
  belongs_to :feature

  # without `presence: true` I get errors when attempting to create a result
  # rubocop:disable Rails/RedundantPresenceValidationOnBelongsTo
  validates :feature, :duration, :environment, :test_run, presence: true
  # rubocop:enable Rails/RedundantPresenceValidationOnBelongsTo
  validates :passed, inclusion: { in: [true, false] }

  default_scope { order(created_at: :desc) }
  scope :passing, -> { where(passed: true) }
  scope :test_run, ->(test_run) { where(test_run:) }

  def self.test_runs
    pluck(:test_run).uniq.map { |time| Time.zone.at(time.to_i) }
  end
end

app/models/user.rb
# frozen_string_literal: true

# user model
class User < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable, :trackable,
         :validatable

  # for api
  def generate_auth_token
    token = SecureRandom.hex
    update!(auth_token: token, token_created_at: Time.zone.now)
    token
  end

  def invalidate_auth_token
    update!(auth_token: nil, token_created_at: nil)
  end
end

app/controllers/api/base_controller.rb
# frozen_string_literal: true

module Api
  # base controller for api - these are not ApplicationControllers
  class BaseController < ActionController::Base # rubocop:disable Rails/ApplicationController
    before_action :require_login!
    helper_method :user_signed_in?, :current_user

    def user_signed_in?
      current_user.present?
    end

    def require_login!
      return true if authenticate_token

      render json: { errors: [{ detail: 'Access denied' }] }, status: :unauthorized
    end

    def current_user
      @current_user ||= authenticate_token
    end

    private

    def authenticate_token
      authenticate_with_http_token do |token, _options|
        User.where(auth_token: token)
            .where(token_created_at: 5.minutes.ago..).first
      end
    end
  end
end

app/controllers/api/features_controller.rb
# frozen_string_literal: true

module Api
  # features controller for api
  class FeaturesController < Api::BaseController
    def create
      feature = Feature.find_or_initialize_by(feature_params)

      if feature.save
        render json: { feature_id: feature.id }
      else
        invalid_feature_creation
      end
    end

    private

    def feature_params
      params.expect(feature: %i[rspec_id description])
    end

    def invalid_feature_creation
      render json: {
        errors: [{ detail: 'Error creating feature' }]
      }, status: :unprocessable_entity
    end
  end
end

app/controllers/api/results_controller.rb
# frozen_string_literal: true

module Api
  # results controller for api
  class ResultsController < Api::BaseController
    def create
      result = Result.new(result_params)

      if result.save
        render json: { result_id: result.id }
      else
        invalid_result_creation
      end
    end

    private

    def result_params
      params.expect(
        result: %i[feature_id duration exception environment passed test_run]
      )
    end

    def invalid_result_creation
      render json: {
        errors: [{ detail: 'Error creating result' }]
      }, status: :unprocessable_entity
    end
  end
end

app/controllers/api/sessions_controller.rb
# frozen_string_literal: true

module Api
  # sessions controller for api
  class SessionsController < Api::BaseController
    skip_before_action :require_login!, only: [:create]

    def create
      resource = User.find_for_database_authentication(
        email: login_params[:email]
      )
      resource ||= User.new

      if resource.valid_password?(login_params[:password])
        auth_token = resource.generate_auth_token
        render json: { auth_token: }
      else
        invalid_login_attempt
      end
    end

    def destroy
      resource = current_user
      resource.invalidate_auth_token
      head :ok
    end

    private

    def login_params
      params.expect(user_login: %i[email password])
    end

    def invalid_login_attempt
      render json: {
        errors: [{ detail: 'Error with your login or password' }]
      }, status: :unauthorized
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# top level controller class
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :authenticate_user!
  before_action :set_timezone

  def set_timezone
    Time.zone = 'Central Time (US & Canada)'
  end
end

app/controllers/features_controller.rb
# frozen_string_literal: true

# features controller
class FeaturesController < ApplicationController
  def index
    @features = Feature.all
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# home controller
class HomeController < ApplicationController
  def show; end
end

app/controllers/results_controller.rb
# frozen_string_literal: true

# results controller
class ResultsController < ApplicationController
  def index
    @feature = Feature.find(params[:feature_id])
    @results = @feature.results
  end
end

app/controllers/test_runs_controller.rb
# frozen_string_literal: true

# test runs controller
class TestRunsController < ApplicationController
  def index
    @test_runs = Result.test_runs
  end

  def show
    time = params[:id].to_datetime.strftime('%s')
    @test_run_results = Result.test_run(time)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# top level helper module
module ApplicationHelper
end

app/views/features/_feature.html.erb
<tr>
  <td><%= link_to feature.rspec_id, feature_results_path(feature.id) %></td>
  <td><%= feature.description %></td>
  <td style="text-align:center"><%= feature.status %></td>
  <td style="text-align:center"><%= feature.last_passed %></td>
</tr>

app/views/features/index.html.erb
<h1>Features</h1>
<%= link_to "Back to Home", root_path %>

<table style="width:100%">
  <thead>
    <tr>
      <th>RSpec ID</th>
      <th>Description</th>
      <th>Status</th>
      <th>Last Passed</th>
    </tr>
  </thead>
  <tbody>
    <%= render @features %>
  </tbody>
</table>

app/views/home/show.html.erb
<div>
  <%= link_to "Features", features_path %>
</div>

<div>
  <%= link_to "Test Runs", test_runs_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroceriesFeaturesResults</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/results/_result.html.erb
<tr style="text-align: center">
  <td><%= result.created_at.to_formatted_s(:long) %></td>
  <td><%= result.duration %></td>
  <td><%= result.exception || 'N/A' %></td>
  <td><%= result.passed %></td>
  <td><%= result.environment %></td>
</tr>

app/views/results/index.html.erb
<h1>Results for "<%= @feature.description %>"</h1>
<%= link_to "Back to Features", features_path %>

<table style="width:100%">
  <thead>
    <tr>
      <th>Timestamp</th>
      <th>Duration</th>
      <th>Exception</th>
      <th>Passed?</th>
      <th>Environment</th>
    </tr>
  </thead>
  <tbody>
    <%= render @results %>
  </tbody>
</table>

app/views/test_runs/index.html.erb
<h1>Test Runs</h1>
<%= link_to "Back to Home", root_path %>

<br><br>

<% @test_runs.each do |test_run| %>
  <div>
    <%= link_to test_run, test_run_path(test_run) %>
  </div>
<% end %>

app/views/test_runs/show.html.erb
<h1>Test results for <%= params[:id] %></h1>
<%= link_to "Back to Test Runs", test_runs_path %>

<table style="width:100%">
  <thead>
    <tr>
      <th>RSpec ID</th>
      <th>Timestamp</th>
      <th>Duration</th>
      <th>Exception</th>
      <th>Passed?</th>
      <th>Environment</th>
    </tr>
  </thead>
  <tbody>
    <% @test_run_results.each do |result| %>
      <tr>
        <td><%= link_to result.feature.rspec_id, feature_results_path(result.feature.id) %></td>
        <td style="text-align:center"><%= result.created_at.to_formatted_s(:long) %></td>
        <td style="text-align:center"><%= result.duration %></td>
        <td style="text-align:center"><%= result.exception || 'N/A' %></td>
        <td style="text-align:center"><%= result.passed %></td>
        <td style="text-align:center"><%= result.environment %></td>
      </tr>
    <% end %>
  </tbody>
</table>